### ISSUE TITLE
Update python-igraph dependency to igraph

### ISSUE THREAD

**Issue by szhorvat** [KellisLab/scdemon#1]
I notice that even though this is recently created GitHub repo, it contains a dependency on the long-deprecated `python-igraph` package name. The updated package name is `igraph`.

https://github.com/search?q=repo%3AKellisLab%2Fscdemon%20python-igraph&type=code

For an explanation, please see https://github.com/igraph/python-igraph/issues/699

**Comment by cboix** [comment]
Fixed, thanks for letting us know.
